
# Source directories
sonar.sources=src,app
sonar.tests=src

# File patterns
sonar.inclusions=**/*.ts,**/*.tsx,**/*.js,**/*.jsx
sonar.exclusions=**/node_modules/**,**/*.test.ts,**/dist/**,**/.next/**,**/*.test.tsx,**/*.test.js,**/test/**,**/globals.css,**/.github/**

# Test patterns
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.test.exclusions=**/node_modules/**

# TypeScript/JavaScript specific settings
# Note: sonar.javascript.lcov.reportPaths works for both JS and TS
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Code coverage
sonar.coverage.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/*.test.tsx,**/*.test.ts,**/*.test.js,**/test/**


# Language settings
sonar.language=ts

# Import paths for TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Quality gate settings
sonar.qualitygate.wait=true




